### ISSUE TITLE
Determine inline documentation generators

### ISSUE THREAD

**Issue by yenWu** [PikoRT/pikoRT#52]
I'm looking for appropriate documentation generators which supported including comments from source files. However, there are two candidates on my list. One is the well-known project, *[Doxygen](http://www.stack.nl/~dimitri/doxygen/index.html)*, and the other one is *[Linuxdoc](https://return42.github.io/linuxdoc/)*, which is a *Sphinx* extension.

As all we knew, *Doxygen* is a really powerful and historical documentation tool for not only generating calling graph but also parsing comments annotated in source files. No doubt, it is the first pick.

*Linuxdoc* is a recently arising project, which is an extension of *[Sphinx](http://www.sphinx-doc.org/en/stable/)* which supports inline documentation in C source files. From 2016, *Linux* start to migrate documentation tool from *DocBook* to *Sphinx*, and is in urgent need of *Linuxdoc*. Moreover, It also backward compatible with existing docs support by *DocBook*. More details you could find it on [How to write kernel documentation](https://www.kernel.org/doc/html/v4.11/doc-guide/index.html).

I have already tested both of them, and they worked excellently.

Here is a comprehensive comparison report, [Comparison of documentation generators](https://en.wikipedia.org/wiki/Comparison_of_documentation_generators), on Wikipedia. It's worth to mention that the license of *Doxygen* is *GPL*, and *Sphinx* is *BSD*. But *Linuxdoc* is *GPLv2* referred to [repo on Github](https://github.com/return42/linuxdoc/tree/master).

Any suggestion is welcome :-)

**Comment by jserv** [comment]
Since #13 (Sphinx documentation generation) contributed by @mlouielu is merged, I defer to Sphinx.
